{% set name = "typst" %}
{% set version = "0.11.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd8debe21d5d22d4cd6c823494537f1356c9954cc2fe6c5db8c76c1b126112dd

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]

test:
  commands:
    - typst --version

about:
  home: https://github.com/typst/typst
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
    - THIRDPARTY_LICENSES.yaml
  summary: A new markup-based typesetting system that is powerful and easy to learn.

extra:
  recipe-maintainers:
    - AdrianFreundQC
    - freundTech
    - pavelzw
