github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test: native_and_emulated
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  version_updates:
    exclude:
    - v23-03-28
    - 23-03-28
    - v23-03-21
    - 23-03-21
    - v23-03-21-2
    - 23-03-21-2
  automerge: true
